"""
Django settings for bible_research project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import textwrap

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Settings Configuration ---
# Use individual environment variables on Vercel, local file otherwise

IS_VERCEL = os.environ.get('VERCEL') == '1'

if IS_VERCEL:
    # On Vercel: Use environment variables directly, no YAML file
    CONFIG_FILE = None

    # Create ca.pem at runtime if database cert is provided
    CA_PEM_PATH = None
    capem_content = os.environ.get('DB_SSL_CERT')
    if capem_content:
        CA_PEM_PATH = '/tmp/ca.pem'
        if not os.path.exists(CA_PEM_PATH):
            lines = capem_content.replace(
                "-----BEGIN CERTIFICATE----- ",
                "-----BEGIN CERTIFICATE-----\n"
            )
            lines = lines.replace(
                " -----END CERTIFICATE-----",
                "\n-----END CERTIFICATE-----"
            )
            base64_content = lines.split("\n", 1)[1].rsplit(
                "\n", 1
            )[0]
            formatted_content = textwrap.fill(base64_content, 64)
            pem_content = (
                f"-----BEGIN CERTIFICATE-----\n"
                f"{formatted_content}\n"
                f"-----END CERTIFICATE-----"
            )
            with open(CA_PEM_PATH, 'w') as f:
                f.write(pem_content)
else:
    # Local development: Use config.yaml from project root
    CONFIG_FILE = BASE_DIR / 'config.yaml'
    CA_PEM_PATH = None

# Load config from the determined path (only for local dev)
if CONFIG_FILE and CONFIG_FILE.exists():
    import yaml
    with open(CONFIG_FILE, 'r') as f:
        config = yaml.safe_load(f)
elif not IS_VERCEL:
    raise FileNotFoundError(
        'Config file does not exist. Please provide config.yaml'
    )
else:
    # On Vercel, no config.yaml needed
    config = {}


def get_env(key, default=None, required=False):
    value = config.get(key, os.environ.get(key, default))
    if required and value is None:
        raise ValueError(f"Required setting '{key}' is not set.")
    return value


SECRET_KEY = get_env('SECRET_KEY', required=True)
DEBUG = get_env('DEBUG', 'False') == 'True'
ESV_KEY = get_env('ESV_KEY')
DBT_KEY = get_env('DBT_KEY')

ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',

    # My apps
    'bible.apps.BibleConfig',
    'annotations.apps.AnnotationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bible_research.middleware.DeviceAndCountryMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

# Allow all Vercel automatically deployed PR preview origins
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*-vincent-uches-projects\.vercel\.app$",
]

ROOT_URLCONF = 'bible_research.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bible_research.wsgi.application'


# Database configuration
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    if IS_VERCEL:
        # On Vercel: Build database config from individual env vars
        db_config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': get_env('DB_NAME', required=True),
            'USER': get_env('DB_USER', required=True),
            'PASSWORD': get_env('DB_PASSWORD', required=True),
            'HOST': get_env('DB_HOST', required=True),
            'PORT': get_env('DB_PORT', '5432'),
        }

        # Add SSL options if certificate is provided
        if CA_PEM_PATH:
            db_config['OPTIONS'] = {
                'sslmode': 'require',
                'sslrootcert': CA_PEM_PATH
            }

        DATABASES = {'default': db_config}
    else:
        # Local: Use DATABASES from config.yaml
        DATABASES = config.get('DATABASES')
        if DATABASES and 'default' in DATABASES:
            opts = DATABASES['default'].get('OPTIONS', {})
            if 'sslrootcert' in opts:
                cert_path = opts['sslrootcert']
                opts['sslrootcert'] = str(BASE_DIR / cert_path)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles', 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'bible_research.authentication.BearerTokenAuthentication',
        (
            'bible_research.authentication.'
            'CSRFExemptSessionAuthentication'
        ),
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Bible Research API',
    'DESCRIPTION': 'API for the Bible Research project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}


def create_log_handler(
    handler_name, level, filename=None, max_bytes=10485760,
    backup_count=10
):
    if DEBUG and filename:
        # Create logs directory if it doesn't exist
        logs_dir = os.path.join(BASE_DIR, 'logs')
        if not os.path.exists(logs_dir):
            os.makedirs(logs_dir)

        return {
            'level': level,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', filename),
            'maxBytes': max_bytes,  # 10MB
            'backupCount': backup_count,
            'formatter': 'verbose',
        }
    else:
        return {
            'level': level,
            'class': 'logging.NullHandler',
        }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': (
                '{levelname} {asctime} {module} {process:d} '
                '{thread:d} {message}'
            ),
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_debug': create_log_handler('file_debug', 'DEBUG', 'debug.log'),
        'file_error': create_log_handler('file_error', 'ERROR', 'error.log'),
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug'],
            'level': 'INFO',
            'propagate': True,
        },
        'tv_archive': {
            'handlers': ['console', 'file_debug'],
            'level': 'DEBUG',
            'propagate': True,
        }
    },
}
