# Generated by Django 4.2.6 on 2025-11-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_note_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(blank=True, help_text='The actual content of the note.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False, help_text='If True, this note is accessible to unauthenticated users.'),
        ),
    ]
