# Generated by Django 4.2.6 on 2026-01-04 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0005_alter_note_note_text_alter_note_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_child_tag_name_per_parent_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name', 'parent_tag')},
        ),
    ]
