# Generated by Django 4.2.6 on 2026-05-21 07:08

import annotations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0006_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=annotations.models.generate_comment_id, editable=False, help_text='Unique identifier for the comment.', max_length=18, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The text content of the comment.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the comment was created.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-deletion flag. Deleted comments are hidden but retained so reply threads remain unbroken.')),
                ('note', models.ForeignKey(help_text='The root note this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='annotations.note')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment for nested replies. Null for top-level comments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='annotations.comment')),
                ('user', models.ForeignKey(help_text='The user who authored this comment.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['note_id'], name='comment_note_id_idx'), models.Index(fields=['parent_comment_id'], name='comment_parent_id_idx')],
            },
        ),
    ]
