# Generated by Django 4.2.6 on 2026-05-21 08:08

import annotations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0007_add_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(default=annotations.models.generate_image_id, editable=False, help_text='Unique identifier for the image (IMG_…).', max_length=18, primary_key=True, serialize=False)),
                ('storage_url', models.URLField(help_text='Canonical GCS URI of the original full-resolution file (e.g. gs://<bucket>/originals/<image_id>/<filename>).', max_length=1024)),
                ('content_type', models.CharField(blank=True, help_text='MIME type captured at upload time (e.g. image/jpeg).', max_length=64)),
                ('size_bytes', models.PositiveIntegerField(blank=True, help_text='File size in bytes, captured at upload time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, help_text='Comment this image is attached to (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotations.comment')),
                ('note', models.ForeignKey(blank=True, help_text='Note this image is attached to (nullable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotations.note')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['comment_id'], name='image_comment_id_idx'), models.Index(fields=['note_id'], name='image_note_id_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('comment__isnull', False), ('note__isnull', True)), models.Q(('comment__isnull', True), ('note__isnull', False)), _connector='OR'), name='image_exactly_one_parent'),
        ),
    ]
