# Generated by Django 4.2.6 on 2026-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_add_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag_position',
            field=models.FloatField(blank=True, help_text='User-defined display order within a tag group. Null means no custom order set (falls back to created_at DESC).', null=True),
        ),
    ]
