# Generated by Django 4.2.6 on 2026-09-04 05:20

import annotations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0009_add_note_tag_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag_position',
            field=models.FloatField(default=annotations.models.get_unix_timestamp, help_text='User-defined display order within a tag group. Defaults to Unix timestamp at creation.'),
        ),
    ]
