# Generated by Django 4.2.6 on 2026-09-10 13:13

import annotations.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0010_alter_note_tag_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPosition',
            fields=[
                ('id', models.CharField(default=annotations.models.generate_reading_position_id, editable=False, help_text='Unique identifier for reading position.', max_length=18, primary_key=True, serialize=False)),
                ('book', models.CharField(help_text="Book name (e.g., 'Genesis', 'John', '1 Chronicles')", max_length=50)),
                ('chapter', models.IntegerField(default=1, help_text='Chapter number (1-based)')),
                ('verse', models.IntegerField(default=1, help_text='First verse in view (for scroll restoration)')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who owns this reading position.', on_delete=django.db.models.deletion.CASCADE, related_name='reading_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Position',
                'verbose_name_plural': 'Reading Positions',
                'db_table': 'reading_positions',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['user', 'book'], name='reading_pos_user_book_idx'), models.Index(fields=['user', '-last_accessed'], name='reading_pos_user_time_idx')],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
