# Generated by Django 4.2.6 on 2026-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0011_readingposition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(condition=models.Q(('tag__isnull', False)), fields=('tag', 'tag_position'), name='unique_tag_position_per_tag'),
        ),
    ]
